package constants

var (
	Constants_1                                                                                                                         = ""
	KeymustbesetintheconnectionconfigurationEdityourconnectionconfigurationfileorsettheGANDIKEYenvironmentvariableandthenrestartselefra = "'key' must be set in the connection configuration. Edit your connection configuration file or set the GANDI_KEY environment variable and then restart selefra"
	Newclientserrs                                                                                                                      = "new clients err: %s"
	Accountinformationnotfound                                                                                                          = "account information not found"
	Constants_2                                                                                                                         = ""
	Constants_4                                                                                                                         = "*"
	Initprovidererrors                                                                                                                  = "init provider error: %s"
	Constants_0                                                                                                                         = ""
	Analysisconfigerrs                                                                                                                  = "analysis config err: %s"
	Constants_3                                                                                                                         = "."
	Providerpulltableerrors                                                                                                             = "provider pull table error: %s"
	Os                                                                                                                                  = "os"
	Errors                                                                                                                              = "errors"
	GANDIKEY                                                                                                                            = "GANDI_KEY"
	V                                                                                                                                   = "v0.0.1"
	Gandi                                                                                                                               = "gandi"
	Notsupported                                                                                                                        = "not_supported"
	Testing                                                                                                                             = "testing"
	SELEFRADATABASEDSN                                                                                                                  = "SELEFRA_DATABASE_DSN"
	Context                                                                                                                             = "context"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable                                                                        = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	NA                                                                                                                                  = "N/A"
)
